export interface Station {
    station: string;
    code: string;
}

export const stations: Station[] = [
    {"station": "Aberdeen", "code": "ABD"},
    {"station": "Apsley", "code": "APS"},
    {"station": "Atherstone", "code": "ATH"},
    {"station": "Aviemore", "code": "AVM"},
    {"station": "Bangor (Gwynedd)", "code": "BNG"},
    {"station": "Berkhamsted", "code": "BKM"},
    {"station": "Birmingham International", "code": "BHI"},
    {"station": "Birmingham New Street", "code": "BHM"},
    {"station": "Blackpool North", "code": "BPN"},
    {"station": "Bletchley", "code": "BLY"},
    {"station": "Bushey", "code": "BSH"},
    {"station": "Carpenders Park", "code": "CPK"},
    {"station": "Carstairs", "code": "CRS"},
    {"station": "Cheddington", "code": "CED"},
    {"station": "Chester", "code": "CTR"},
    {"station": "Coventry", "code": "COV"},
    {"station": "Crewe", "code": "CRE"},
    {"station": "Dundee", "code": "DEE"},
    {"station": "Edinburgh Waverley", "code": "EDB"},
    {"station": "Fort William", "code": "FTW"},
    {"station": "Glasgow Central", "code": "GLC"},
    {"station": "Gleneagles", "code": "GLE"},
    {"station": "Gretna Green", "code": "GEA"},
    {"station": "Harrow & Wealdstone", "code": "HRW"},
    {"station": "Harlesden", "code": "HDN"},
    {"station": "Headstone Lane", "code": "HDL"},
    {"station": "Hemel Hempstead", "code": "HML"},
    {"station": "Inverness", "code": "INV"},
    {"station": "Kensal Green", "code": "KNL"},
    {"station": "Kenton", "code": "KNT"},
    {"station": "Kilburn High Road", "code": "KBN"},
    {"station": "Kings Langley", "code": "KGL"},
    {"station": "Lancaster", "code": "LAN"},
    {"station": "Leighton Buzzard", "code": "LBZ"},
    {"station": "Leuchars", "code": "LEU"},
    {"station": "Liverpool Lime Street", "code": "LIV"},
    {"station": "Long Buckby", "code": "LBK"},
    {"station": "Manchester Piccadilly", "code": "MAN"},
    {"station": "Milton Keynes Central", "code": "MKC"},
    {"station": "Northampton", "code": "NMP"},
    {"station": "Oxenholme Lake District", "code": "OXN"},
    {"station": "Penrith North Lakes", "code": "PNR"},
    {"station": "Perth", "code": "PTH"},
    {"station": "Pitlochry", "code": "PIT"},
    {"station": "Preston", "code": "PRE"},
    {"station": "Queen's Park (London)", "code": "QPW"},
    {"station": "Rugby", "code": "RUG"},
    {"station": "South Hampstead", "code": "SOH"},
    {"station": "Stafford", "code": "STA"},
    {"station": "Stirling", "code": "STG"},
    {"station": "Stockport", "code": "SPT"},
    {"station": "Stonebridge Park", "code": "SBP"},
    {"station": "Tring", "code": "TRI"},
    {"station": "Watford High Street", "code": "WFH"},
    {"station": "Watford Junction", "code": "WFJ"},
    {"station": "Wembley Central", "code": "WMB"},
    {"station": "Willesden Junction", "code": "WIJ"},
    {"station": "Wigan North Western", "code": "WGN"},
    {"station": "Wolverton", "code": "WOL"}
]
